# Dont print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the ">" symbol in the prompt with 
[character] # the name o fth emodule we are configuring is "character"
success_symbol ="[>](bold green)" # The success_symbol is set to "#" with color bold green

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
